# -*- coding: utf-8 -*-
"""Data Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVm4kOjumBzIZFnxiHoW965p8sODfhPu
"""

# importing
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# reading data set into variable
dataSetPath = "/content/drive/MyDrive/Inspirit AI Research/dataset.csv"
dataSet = pd.read_csv(dataSetPath)

dataSet.head()

plt.figure()
plt.scatter(dataSet.diameter, dataSet.e)
plt.xlabel("Diameter")
plt.ylabel("Eccentricity")

plt.figure()
plt.hist(dataSet.e, bins = 1000)
plt.xlabel("Eccentricity")
plt.ylabel("Count")

plt.figure()
plt.scatter(dataSet.moid, dataSet.moid_ld)
plt.xlabel("moid")
plt.ylabel("moid_ld")

# On kaggle it looks like the difference between both of these axis is just the units and there is some sort of linear conversion to go between units.

plt.figure()
plt.scatter(dataSet.om, dataSet.w)
plt.xlabel("Omega")
plt.ylabel("w")

# I am not sure why the whole graph is filled, does it mean something important?

plt.figure()
plt.scatter(dataSet.a, dataSet.q)
plt.xlabel("Semi-major Axis")
plt.ylabel("Perihelion Distance")

# Looks like almost all samples have around the same semi-major axis value.
# You can plot the orbit of the asteroids just like you would plot an elipse. The data has all the information I would need to do this.
# I will use machine learning to predict the class of an asteroid.

# PRE PROCESSING THE DATA
# duplicating data set to pre process data
processedDataSet = dataSet.copy()
# removing unecessary features from data set
processedDataSet.drop(['id','spkid','full_name','pdes','name','prefix','neo','pha','diameter_sigma','orbit_id','epoch'], axis=1, inplace=True)
processedDataSet.drop(['equinox','tp','tp_cal','per_y','om','moid','moid_ld','sigma_e','sigma_a','sigma_q','sigma_i','sigma_om'], axis=1, inplace=True)
processedDataSet.drop(['sigma_ad','sigma_n','sigma_tp','sigma_per','rms','sigma_w','sigma_ma','epoch_mjd','epoch_cal'], axis=1, inplace=True)
# finding null values
np.sum(processedDataSet.isnull())
# changing null values to median values
processedDataSet['H'].fillna(processedDataSet['H'].median(), inplace=True)
processedDataSet['diameter'].fillna(processedDataSet['diameter'].median(), inplace=True)
processedDataSet['albedo'].fillna(processedDataSet['albedo'].median(), inplace=True)
processedDataSet['ma'].fillna(processedDataSet['ma'].median(), inplace=True)
processedDataSet['ad'].fillna(processedDataSet['ad'].median(), inplace=True)
processedDataSet['per'].fillna(processedDataSet['per'].median(), inplace=True)

# PREPARING DATA FOR MODEL
# setting y vector and x matrix
y = processedDataSet['class']
x = processedDataSet.drop(columns='class')

# reading the x and y to a file
x.to_csv("/content/drive/MyDrive/Inspirit AI Research/dataSetX.csv")
y.to_csv("/content/drive/MyDrive/Inspirit AI Research/dataSetY.csv")

# REFERENCES:
# https://matplotlib.org/2.0.2/mpl_toolkits/mplot3d/tutorial.html How to plot in 3D with matplotlib
# https://www.kaggle.com/code/wumanandpat/asteroid-dataset-exploration Kaggle entry on using the dataset that I used
# https://www.kaggle.com/datasets/sakhawat18/asteroid-dataset My dataset
# https://en.wikipedia.org/wiki/Orbit_modeling How to model asteroid orbits
# https://www.researchgate.net/profile/Mir-Sakhawat-Hossain/publication/367413592_Machine_Learning_Approaches_for_Classification_and_Diameter_Prediction_of_Asteroids/links/63e37da8c002331f72624d12/Machine-Learning-Approaches-for-Classification-and-Diameter-Prediction-of-Asteroids.pdf
# above paper also uses machine learning to classify asteroid orbits
# https://arxiv.org/pdf/2308.15457.pdf: About data augmentation techniqueds and SMOTE
# https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html
# https://ssd-api.jpl.nasa.gov/doc/sbdb_filter.html
# https://towardsdatascience.com/building-our-first-neural-network-in-keras-bdc8abbc17f5 How to buold a custom neural network
# https://en.wikipedia.org/wiki/Kirkwood_gap About kirkwood gaps
# https://www.youtube.com/watch?v=Bsudo7jbMow How to set up weights and biases
# https://www.youtube.com/watch?v=9zrmUIlScdY Hyperparameter tuning with weights and biases
# https://keras.io/api/models/model_saving_apis/model_saving_and_loading/ Saving a model to save the neural network weights